---
data_root_path: "/mnt/e/UBFC_DATASET/"                  # raw data path
dataset_path: "/mnt/e/preprocessed/"                    # preprocessed data save/load path
model_save_path: "/mnt/e/models/rppg/"                  # model save path

preprocess:
  flag: true                                            # true: preprocess, false: not preprocess
  process_num: 5                                       # number of task per process for multiprocessing
  fixed_position: 1                                     # 0: face tracking, 1: fixed position
  face_detect_algorithm: 1                              # 1: face recognition, 2: FaceMesh
  larger_box_coef: 1.5
  image_size: 128                                       # cropped image size
  dataset_name: PURE                                    # dataset name


fit:
  model: DeepPhys
  dataset_name: PURE                                    # dataset name
  time_length: 180                                       # 每个batch的帧数
  overlap_interval: 0                                  # overlap interval of input
  img_size: 128                                        # cropped image size
  larger_box_coef: 1.5                                 # larger box coefficient
  train_flag: true                                     # true: train, false: test
  eval_flag: true                                      # true: eval, false: not eval
  eval_interval: 100                                     # eval interval
  debug_flag: true                                    # true: debug, false: not debug
  model_save_flag: true                                # true: save model, false: not save model


  train:
    dataset_name: PURE                                    # dataset name
    shuffle: true                                       # true: shuffle, false: not shuffle
    fs: 30                                              # video fps
    batch_size: 1                                      # batch size
    learning_rate: 0.009                               # learning rate
    epochs: 150                                          # epoch
    loss: MSE                                          # loss function
    optimizer: AdamW                                   # optimizer

  test:
    dataset_name: PURE                                    # dataset name
    shuffle: false                                      # true: shuffle, false: not shuffle
    fs: 30                                              # video fps
    batch_size: 1                                      # batch size
    vital_type: HR                                     # HR or HRV
    cal_type : PEAK                                    # PEAK or FFT
    bpf: None                                          # band pass filter, None: not use, 60~100bpm : [1, 1.67], 45~150bpm : [0.75, 2.5]
    metrics: [MAE, RMSE, MAPE, Pearson]                       # metric
    eval_time_length: 5                               # second



